[book]
authors = ["Denys Vuika"]
language = "en"
multilingual = false
src = "docs"
title = "ADF Starter Kit for ACS"

[output.html]
git-repository-url = "https://github.com/DenysVuika/adf-starter-acs"
site-url = "/adf-starter-acs/"
